'use strict';
const { bad, ok, bearer, firebase } = require('./_firebase');
const READ_ROLES=['Super Admin','Admin','Management','Head Office','GE Team','Branch Office'];
function canRead(a){return READ_ROLES.includes(a?.role)&&String(a?.status||'Active').toLowerCase()==='active'}
function canEdit(a){return canRead(a)&&(a.role==='Super Admin'||(a.role==='Admin'&&['Editor','Admin'].includes(String(a.accessLevel||'Viewer'))))}
function clean(v,max=1000){const s=String(v??'').trim();if(s.length>max)throw Object.assign(new Error('Input terlalu panjang.'),{statusCode:400,code:'INVALID_INPUT'});return s}
async function actorFor(event){const token=bearer(event);if(!token)throw Object.assign(new Error('Authentication required.'),{statusCode:401,code:'AUTH_REQUIRED'});const {auth,db}=firebase();let decoded;try{decoded=await auth.verifyIdToken(token,true)}catch{throw Object.assign(new Error('Session tidak valid.'),{statusCode:401,code:'AUTH_INVALID'})}const snap=await db.collection('users').doc(decoded.uid).get();if(!snap.exists)throw Object.assign(new Error('Profile tidak ditemukan.'),{statusCode:403,code:'PROFILE_NOT_FOUND'});const actor={id:decoded.uid,...snap.data()};if(!canRead(actor))throw Object.assign(new Error('Akses ditolak.'),{statusCode:403,code:'FORBIDDEN'});return{db,actor}}
function normalize(b){const out={};for(const k of ['region','airport','name','serviceCategory','serviceType','pic','currency','priceDisplay','startDate','startDisplay','endDate','endDisplay','documentNumber','documentType','documentStatus','remarks','documentName','documentKey','status'])if(Object.prototype.hasOwnProperty.call(b,k))out[k]=clean(b[k],k==='remarks'?2000:500);if(Object.prototype.hasOwnProperty.call(b,'pricePerPax'))out.pricePerPax=Number(b.pricePerPax||0);return out}
exports.handler=async event=>{try{if(!['GET','POST'].includes(event.httpMethod))return bad(405,'METHOD_NOT_ALLOWED','Method not allowed.');const {db,actor}=await actorFor(event);if(event.httpMethod==='GET'){const snap=await db.collection('lounges').get();return ok({lounges:snap.docs.map(d=>({firestoreId:d.id,id:d.data()?.id??d.id,...d.data()})),meta:{source:'Firestore',collection:'lounges'}})}if(!canEdit(actor))return bad(403,'FORBIDDEN','Lounge memerlukan Access Level Editor atau Admin.');let b={};try{b=JSON.parse(event.body||'{}')}catch{return bad(400,'INVALID_JSON','Request body tidak valid.')}const action=String(b.action||'').toUpperCase();if(action==='CREATE'){const data=normalize(b);data.createdAt=new Date().toISOString();data.updatedAt=data.createdAt;data.updatedBy=actor.id;const ref=db.collection('lounges').doc();await ref.set(data);return ok({lounge:{firestoreId:ref.id,id:Date.now(),...data}})}if(action==='UPDATE'){const id=clean(b.firestoreId||b.id,180);const ref=db.collection('lounges').doc(id);const snap=await ref.get();if(!snap.exists)return bad(404,'NOT_FOUND','Lounge tidak ditemukan.');const data=normalize(b);data.updatedAt=new Date().toISOString();data.updatedBy=actor.id;await ref.set(data,{merge:true});return ok({lounge:{firestoreId:ref.id,id:snap.data()?.id??Date.now(),...snap.data(),...data}})}if(action==='DELETE'){const id=clean(b.firestoreId||b.id,180);await db.collection('lounges').doc(id).delete();return ok({deleted:id})}return bad(400,'INVALID_ACTION','Action tidak didukung.')}catch(e){return bad(e.statusCode||500,e.code||'LOUNGES_FAILED',e.statusCode?e.message:'Lounge request gagal.')}};
