'use strict';
const{json,actor,FieldValue}=require('./firebase');
const GROUPS=new Set(['airports','initiatives','news','touchpoints','documents','projectEvents','loungePurchases','loungeVisitors','stationMaterials','boSpaces','serviceProcurement','airportSystems','skyPriority','touchpointStandards','gasoMaster','gasoServiceSupport','gasoPlanningService','personnel','articles','announcements','faqs','inbox','auditLogs','lounges','standardContent','portalManager','contactMessages','guestbook']);
const normRole=r=>({'SuperAdmin':'Super Admin','HeadOffice':'Head Office','BranchOffice':'Branch Office'}[r]||r);
const stations=a=>{if(normRole(a.role)==='Super Admin'||String(a.scopeType||'').toUpperCase()==='ALL')return null;return new Set([...(a.assignedStations||[]),...(a.airports||[])].map(x=>String(x).trim().toUpperCase()).filter(Boolean))};
const station=x=>String(x?.stationCode||x?.airport||x?.station||x?.relatedAirport||'').trim().toUpperCase();
const scoped=(a,x)=>{const s=stations(a);return !s||!station(x)||s.has(station(x))};
const sanitize=x=>{const y={...x};delete y.password;delete y.passwordHash;delete y.temporaryPassword;return y};
function writable(a,c){const role=normRole(a.role),level=String(a.accessLevel||'');if(role==='Super Admin')return true;if(['users','auditLogs','portalManager'].includes(c))return role==='Admin';return role==='Admin'||['Editor','Admin','Approver'].includes(level)}
function refFor(db,c,id=''){if(c==='users')return id?db.collection('users').doc(String(id)):db.collection('users').doc();const base=db.collection('portalData').doc(c).collection('records');return id?base.doc(String(id)):base.doc()}
async function readGroup(db,c){if(c==='users')return (await db.collection('users').get()).docs;if(!GROUPS.has(c))throw Error(`Data group tidak dikenal: ${c}`);return (await db.collection('portalData').doc(c).collection('records').get()).docs}
exports.handler=async e=>{try{const{db,a}=await actor(e);a.role=normRole(a.role);
 if(e.httpMethod==='GET'){const cs=String(e.queryStringParameters?.collections||'').split(',').map(x=>x.trim()).filter(Boolean);const out={};for(const c of cs){let docs=await readGroup(db,c);let rows=docs.map(d=>({id:d.id,...sanitize(d.data())}));if(c==='inbox'&&!['Super Admin','Admin'].includes(a.role))rows=rows.filter(x=>String(x.recipientId||'')===String(a.id));if(!['initiatives','inbox','users','auditLogs'].includes(c))rows=rows.filter(x=>scoped(a,x));out[c]=rows}return json(200,{ok:true,source:'Firestore portalData/{group}/records',collections:out,actor:a})}
 if(e.httpMethod==='POST'){const b=JSON.parse(e.body||'{}'),c=String(b.collection||''),action=String(b.action||'').toUpperCase();if(c!=='users'&&!GROUPS.has(c))throw Error('Data group tidak dikenal');if(!writable(a,c))return json(403,{ok:false,message:'Tidak memiliki hak edit'});const ref=refFor(db,c,b.id);if(action==='DELETE'){await ref.delete();return json(200,{ok:true,result:{id:ref.id,deleted:true}})}if(!['CREATE','UPDATE'].includes(action))throw Error('Action tidak valid');const data={...(b.data||{}),updatedAt:FieldValue.serverTimestamp(),updatedBy:a.id};if(action==='CREATE'){data.createdAt=FieldValue.serverTimestamp();data.createdBy=a.id}delete data.id;delete data.password;delete data.temporaryPassword;if(!scoped(a,data))return json(403,{ok:false,message:'Data di luar station scope'});await ref.set(data,{merge:action==='UPDATE'});return json(200,{ok:true,result:{id:ref.id}})}
 return json(405,{ok:false,message:'Method not allowed'})}catch(x){return json(x.status||500,{ok:false,message:x.message||'Server error'})}};
