[build]
  command = "npm --prefix netlify/functions install --omit=dev --ignore-scripts"
  publish = "."
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
